#welcome screen

def welcome
  puts " "
  puts "Welcome to MASTERMIND"
  puts "copyright: NoobMasterJONA 2022-2023"
  puts "all rights reserved"
  puts " "
  puts "Enter your name"
  player=gets.chomp.downcase
  puts " "
  puts "Welcome #{player}!"
  puts "Use the digits 1-6 to guess the 4 digit code generated by the computer"
  puts "o means a digit from the code is present in the guess, but not in the right position"
  puts "x means a digit from the code is present in the right position in your guess"
  puts "you have8 tries to guess the code."
  puts ""
  puts "GOODLUCK!"
  puts "Press Enter to continue"
  puts " "
  start=gets
  game 
end 


def game
  code=code_gen
  codetext=""
  g=Array.new(4, 0)
  puts "Code is generated"
  for i in 1..8
    puts " "
    guess=""
    puts "Enter guess#{i}"
    g=gets.to_i.digits.reverse 
    for q in 0..3
      guess+=g[q].to_s
    end
    puts "Guess: #{guess}"
    cluetext=clue(g,code)
    puts "Clue: #{cluetext}"
    if cluetext=="xxxx"
      puts "Congrats, you found the code!"
      puts "YOU WIN!"
      break 
    end 
    if i==8
      puts "You lost!"
      for h in 0..3
        codetext+=code[h].to_s
      end 
      puts "The code was #{codetext}"
    end 
  end 
  
end

#purifies the guess to configure repeated numbers
def purify(g,c)
  #puts "code = #{c} ,guess= #{g
  position=-1
  repeat=g.detect{ |e| g.count(e) > 1 }
  for i in 0..3
    if g[i]==repeat
      if g[i]==c[i]
        position=i 
        for j in 0..3
          if g[j]==repeat
            g[j]=0
          end 
        end 
        g[i]=repeat 
      end
    end 
  end 
  index=nil 
  if position==-1
    index=g.find_index(repeat)
    for k in 0..3
      if g[k]==repeat
        g[k]=0
      end 
    end
    g[index]=repeat
  end 
  #puts "new guess= #{g}"
  return g 
end


#gets clue output for each guess
#x=0 o=1 _=2 
def clue(guess,code)
  guessval=2
  clue_arr=Array.new(4) 
  clue=""
  #puts "code= #{code}"
  #puts "guess = #{guess}"
  chopped_guess=guess.uniq
  for p in 0..1
    if chopped_guess.length!=guess.length
      guess=purify(guess,code)
    end 
    if guess.uniq.length==guess.length
      break
    end 
  end 
  for i in 0..3
    guessval=2
    present=code.include?(guess[i])
    if present==true
      guessval=1
      position=code.find_index(guess[i])
      #puts "position= #{position}"
      if position==i 
        guessval=0
      end
    end
    clue_arr[i]=guessval 
    #puts "clue array= #{clue_arr}"
    #clue+=guessval 
  end
  clue_arr=clue_arr.sort
  for l in 0..3
    if clue_arr[l]==0
      clue=clue+"x"
    elsif clue_arr[l]==1
      clue=clue+"o"
    else
      clue=clue+""
    end 
  end 
  return clue 
end


#generates unique code without repeating digits 
def code_gen
  code=Array.new(4, 0)
  for i in 0..3
    digit=rand(6)
    digit+=1
    code[i]=digit
  end 
  code=code.uniq
  if code.length<4
    code_gen
  else
    return code
  end 
end



welcome 
#([2,1,4,1], [1,2,3,4])